version: '3'

services:
    send_sms:
        build:
            context: ./
            dockerfile: send_sms.Dockerfile
        image: reikolee/send_sms:2.0
        restart: always
        environment:
            PYTHONUNBUFFERED: 1
        ports:
            - "5566:5566"
        #Order: 5000
        #Activity: 5001
        #Shipper: 5002
        #Rate: 5003
        #DropPoint: 5004
        #Valuing: 5005
        #PickParcel: 5006
        #CreateDelivery: 5006
        #UpdateDelivery: 5007
        #AcceptDelivery: 5008

        #Email: 9000
        #Sms: 5566