version: '3'

services:
    send_sms:
        build:
            context: ./
            dockerfile: send_sms.Dockerfile
        image: reiko/send_sms:2.0
        restart: always
        depends_on:
            - rabbitmq
        environment:
            PYTHONUNBUFFERED: 1
        ports:
            - "5566:5566"
    #Order: 5000
    order:
        build:
            context: ./
            dockerfile: order.Dockerfile
        image: pochien.lin/order:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
        ports:
            - "5000:5000"
    #Activity: 5001
    activity:
        build:
            context: ./
            dockerfile: activity.Dockerfile
        image: reiko/activity:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
        ports:
            - "5001:5001"
    #Shipper: 5002
    shipper:
        build:
            context: ./
            dockerfile: shipper.Dockerfile
        image: pochien.lin/shipper:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
        ports:
            - "5002:5002"
        #Rate: 5003
        #DropPoint: 5004
        #Valuing: 5005
        #PickParcel: 5006
    #Create Order: 5007

    create_order:
        build:
            context: ./
            # To add create_order.Dockerfile
            dockerfile: create_order.Dockerfile
        image: pochienlin/create_order:1.0
        restart: always
        depends_on:
            - activity
            - order
            - shipper
            - send_sms
            - email
            - rabbitmq
            - sendgrid
        ports:
            - "5007:5007"

        #UpdateDelivery: 5008
    update_order:
        build:
            context: ./
            # To add create_order.Dockerfile
            dockerfile: update_order.Dockerfile
        image: 889090/update_order:1.0
        restart: always
        # depends_on:
        #     - activity
        #     - order
        #     - shipper
        #     - send_sms
        #     - email
        ports:
            - "5008:5008"


        #AcceptDelivery: 5009

    #Email: 9000
    email:
        build:
            context: ./
            # To add create_order.Dockerfile
            dockerfile: email.Dockerfile
        image: pochien.lin/email_test:1.0
        restart: always
        depends_on:
            - sendgrid
            - rabbitmq
        ports:
            - "9000:9000"
    #Sms: 5566
    # sendgrid
    sendgrid:
        build:
            context: ./
        image: sendgrid/sendgrid-python
        restart: always
        ports:
            - "5011:5011"
    #rabbitmq
    # rabbitmq:
    #     image: rabbitmq:3-management-alpine
    #     container_name: 'rabbitmq'
    #     ports:
    #         - 5672:5672
    #         - 15672:15672
    #     volumes:
    #         - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #         - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    #     networks:
    #         - rabbitmq_go_net
    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
networks:
  rabbitmq_go_net:
    driver: bridge