version: '3.8'

volumes:
    rabbitmq_data:

services:
    ##################################
    # RabbitMQ: The messaging broker #
    ##################################
    rabbitmq:
        image: rabbitmq:3-management
        hostname: camel-rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - rabbitmq_data:/var/lib/rabbitmq

    send_sms:
        build:
            context: ./
            dockerfile: send_sms.Dockerfile
        image: reikolee/send_sms:2.1
        restart: always
        depends_on:
            - rabbitmq
            - activity
        environment:
            rabbit_host: camel-rabbitmq
            rabbit_port: 5672
            PYTHONUNBUFFERED: 1
        ports:
            - "5566:5566"
    #Order: 5000
    order:
        build:
            context: ./
            dockerfile: order.Dockerfile
        image: reikolee/order:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
        ports:
            - "5000:5000"
    #Activity: 5001
    #####################################################
    # Activity: The Activity Log Consumber microservice #
    #####################################################
    activity:
        build:
            context: ./
            dockerfile: activity.Dockerfile
        image: reikolee/activity:1.0
        restart: always
        depends_on:
            - rabbitmq
        environment:
            rabbit_host: camel-rabbitmq
            rabbit_port: 5672
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
            PYTHONUNBUFFERED: 1

    #########################################################
    # Activityhttp: The Activity Log Consumber microservice #
    #########################################################
    activityhttp:
        build:
            context: ./
            dockerfile: activityhttp.Dockerfile
        image: reikolee/activityhttp:1.0
        restart: always
        environment:
            dbURL: 'mysql+mysqlconnector://is213@localhost:3306/camelDB'
            PYTHONUNBUFFERED: 1

    #Shipper: 5002
    shipper:
        build:
            context: ./
            dockerfile: shipper.Dockerfile
        image: reikolee/shipper:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
        ports:
            - "5002:5002"
    
    #Rate: 5003
    rate:
        build:
            context: ./
            dockerfile: rate.Dockerfile
        image: nicwongkw/rate:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
        ports:
            - "5003:5003"

    #DropPoint: 5004
    droppoint:
        build:
            context: ./
            dockerfile: droppoint.Dockerfile
        image: nicwongkw/droppoint:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelDB
        ports:
            - "5004:5004"

        #Valuing: 5005
        #PickParcel: 5006
    #Create Order: 5007

    create_order:
        build:
            context: ./
            # To add create_order.Dockerfile
            dockerfile: create_order.Dockerfile
        image: reikolee/create_order:1.0
        restart: always
        depends_on:
            - activity
            - order
            - shipper
            - send_sms
            - email
            - rabbitmq
        environment:
            rabbit_host: camel-rabbitmq
            rabbit_port: 5672
        ports:
            - "5007:5007"

    #update_order: 5008
    update_order:
        build:
            context: ./
            # To add create_order.Dockerfile
            dockerfile: update_order.Dockerfile
        image: reikolee/update_order:1.0
        restart: always
        depends_on:
            - order
            - activity
            - rabbitmq
            - send_sms
            - email
        environment:
            rabbit_host: camel-rabbitmq
            rabbit_port: 5672
        ports:
            - "5008:5008"
    #AcceptDelivery: 5009
    #Email: 9000
    email:
        build:
            context: ./
            # To add create_order.Dockerfile
            dockerfile: email.Dockerfile
        image: reikolee/email_test:1.0
        restart: always
        depends_on:
            - rabbitmq
            - activity
        environment:
            rabbit_host: camel-rabbitmq
            rabbit_port: 5672
        ports:
            - "9000:9000"
    #Sms: 5566
    # sendgrid
    # sendgrid:
    #     # build:
    #     #     context: ./
    #     image: sendgrid/sendgrid-python
    #     restart: always
    #     ports:
    #         - "5011:5011"
    #rabbitmq
    # rabbitmq:
    #     image: rabbitmq:3-management-alpine
    #     container_name: 'rabbitmq'
    #     ports:
    #         - 5672:5672
    #         - 15672:15672
    #     volumes:
    #         - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #         - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    #     networks:
    #         - rabbitmq_go_net
    # rabbitmq:
    #     container_name: "rabbitmq"
    #     image: rabbitmq:3.8-management-alpine
    #     environment:
    #         - RABBITMQ_DEFAULT_USER=guest
    #         - RABBITMQ_DEFAULT_PASS=guest
    #     ports:
    #         # AMQP protocol port
    #         - '5672:5672'
    #         # HTTP management UI
    #         - '15672:15672'
networks:
    rabbitmq_go_net:
        driver: bridge
