version: '3.8'

volumes:
    rabbitmq_data:

services:
    send_sms:
        build:
            context: ./
            dockerfile: send_sms.Dockerfile
        image: reiko/send_sms:2.0
        restart: always
        environment:
            PYTHONUNBUFFERED: 1
        ports:
            - "5566:5566"
    #Order: 5000
    order:
        build:
            context: ./
            dockerfile: order.Dockerfile
        image: pochien.lin/order:1.0
        restart: always
        environment:
            #let's change the main db to name camelcourier
            dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/camelcourier
        ports:
            - "5000:5000"


        #Activity: 5001
        #Shipper: 5002
        #Rate: 5003
        #DropPoint: 5004
        #Valuing: 5005
        #PickParcel: 5006
    #CreateDelivery: 5007

    # create_order:
    #     build:
    #         context: ./
    #         # To add create_order.Dockerfile
    #         dockerfile: create_order.Dockerfile
    #     image: pochienlin/create_order:1.0
    #     restart: always
    #     depends_on:
    #         - activity
    #         - order
    #         - shipper
    #         - send_sms
    #         - email
    #     ports:
    #         - "5007:5007"

        #UpdateDelivery: 5008
    update_order:
        build:
            context: ./
            # To add create_order.Dockerfile
            dockerfile: update_order.Dockerfile
        image: 889090/update_order:1.0
        restart: always
        # depends_on:
        #     - activity
        #     - order
        #     - shipper
        #     - send_sms
        #     - email
        ports:
            - "5008:5008"


        #AcceptDelivery: 5009

        #Email: 9000
        #Sms: 5566
    
    ##################################
    # RabbitMQ: The messaging broker #
    ##################################
    rabbitmq:
        image: rabbitmq:3-management
        hostname: camel-rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - rabbitmq_data:/var/lib/rabbitmq
    
    #####################################################
    # Activity: The Activity Log Consumber microservice #
    #####################################################
    activity_log:
        build:
        context: ./
        dockerfile: activity.Dockerfile
        image: vasng/activity:1.0
        restart: always
        depends_on:
        - rabbitmq
        environment:
        rabbit_host: rabbitmq
        rabbit_port: 5672
        PYTHONUNBUFFERED: 1